# Generated by Django 5.1.6 on 2025-03-06 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmproduce',
            name='cig',
        ),
        migrations.RemoveField(
            model_name='farmproduce',
            name='quantity',
        ),
        migrations.AddField(
            model_name='commoninterestgroup',
            name='number_of_farms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commoninterestgroup',
            name='total_units_current_cycle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commoninterestgroup',
            name='total_units_last_cycle',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commoninterestgroup',
            name='unit_of_measure',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='cigs',
            field=models.ManyToManyField(blank=True, related_name='farms_registered', to='core.commoninterestgroup'),
        ),
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='total_units',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='unit_of_measure',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AddField(
            model_name='locality',
            name='agro_technician',
            field=models.OneToOneField(blank=True, limit_choices_to={'user_type': 'agro'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='in_charge_locality', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agro_technicians', to='core.locality'),
        ),
        migrations.AddField(
            model_name='user',
            name='managed_cigs',
            field=models.ManyToManyField(blank=True, related_name='managing_agrotechs', to='core.commoninterestgroup'),
        ),
        migrations.AlterField(
            model_name='farmproduce',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_produces', to='core.farm'),
        ),
        migrations.CreateModel(
            name='AgriculturalCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_week', models.CharField(max_length=20)),
                ('end_week', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('cig', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agri_cycle', to='core.commoninterestgroup')),
                ('farm_produce', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle', to='core.farmproduce')),
            ],
        ),
        migrations.AddField(
            model_name='commoninterestgroup',
            name='current_cycle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_cig', to='core.agriculturalcycle'),
        ),
        migrations.AddField(
            model_name='farmproduce',
            name='agricultural_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produces', to='core.agriculturalcycle'),
        ),
    ]
