# Generated by Django 5.1.6 on 2025-03-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_farmproduce_cig_remove_farmproduce_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmproduce',
            name='cig',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farm_produces', to='core.commoninterestgroup'),
        ),
    ]
